In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB


In [12]:
datasets = pd.read_csv("Dataset3.csv")
arr = datasets.values
print(datasets)
le=LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values
X[ : ,0] = le.fit_transform(X[ : ,0])
X[ : ,1] = le.fit_transform(X[ : ,1])
X[ : ,2] = le.fit_transform(X[ : ,2])
X[ : ,3] = le.fit_transform(X[ : ,3])
#Y[ : ,0] = le.fit_transform(Y[ : ,0])
onehotencoder = OneHotEncoder()
Outlook_encoded = onehotencoder.fit_transform(X[ :, 0].reshape(-1,1)).toarray()
Temp_encoded = onehotencoder.fit_transform(X[ :, 1].reshape(-1,1)).toarray()
Humidity_encoded = onehotencoder.fit_transform(X[ :, 2].reshape(-1,1)).toarray()
Wind_encoded = onehotencoder.fit_transform(X[ :, 3].reshape(-1,1)).toarray()
Play_encoded = onehotencoder.fit_transform(Y.reshape(-1,1)).toarray()

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [13]:
features= np.array(list(zip(Outlook_encoded,Temp_encoded,Humidity_encoded,Wind_encoded)),dtype=object)
features = features.flatten()
print("Features: ", features)
print("Target: ",Play_encoded)

Features:  [array([0., 1., 0.]) array([0., 1., 0.]) array([1., 0.])
 array([0., 1., 0.]) array([0., 1., 0.]) array([0., 1., 0.])
 array([0., 1.]) array([0., 0., 1.]) array([1., 0., 0.])
 array([0., 1., 0.]) array([1., 0.]) array([0., 1., 0.])
 array([0., 1., 0.]) array([0., 0., 1.]) array([1., 0.])
 array([0., 1., 0.]) array([0., 0., 1.]) array([1., 0., 0.])
 array([1., 0.]) array([0., 1., 0.]) array([1., 0., 0.])
 array([1., 0., 0.]) array([0., 1.]) array([1., 0., 0.])
 array([1., 0., 0.]) array([1., 0., 0.]) array([0., 1.])
 array([0., 1., 0.]) array([0., 1., 0.]) array([0., 0., 1.])
 array([1., 0.]) array([0., 1., 0.]) array([1., 0., 0.])
 array([1., 0., 0.]) array([1., 0.]) array([1., 0., 0.])
 array([0., 0., 1.]) array([0., 0., 1.]) array([1., 0.])
 array([0., 0., 1.]) array([0., 1., 0.]) array([1., 0., 0.])
 array([0., 1.]) array([0., 0., 1.]) array([1., 0., 0.])
 array([0., 0., 1.]) array([0., 1.]) array([1., 0., 0.])
 array([1., 0., 0.]) array([0., 1., 0.]) array([1., 0.])
 arr

In [24]:

from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(X,
Y, test_size = 0.05, random_state = 4)
print(data_train.shape,target_train.shape)
     

(13, 4) (13,)


In [25]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [26]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.0


In [27]:

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
     

precision: [0. 0.]
recall: [0. 0.]


/Users/yashthakkar/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yashthakkar/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
##(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-mal’, and Wind = ’False’?

In [ ]:
gnb.predict()

# for 50 percentage

In [20]:

from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(X,
Y, test_size = 0.5, random_state = 4)
print(data_train.shape,target_train.shape)

(7, 4) (7,)


In [21]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [22]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.2857142857142857


In [23]:

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.16666667 1.        ]
recall: [1.         0.16666667]
